# Assignment Day 28

Question 1:
    
Create one array of actual values and another array of predicted values. Compare the two sets

with the confusion matrix.


In [2]:
import numpy as np


In [3]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [7]:
expected = np.array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0])
predicted = np.array([1, 0, 0, 1, 0, 0, 1, 1, 1, 0])
print(expected)
print('')
print(predicted)
results = confusion_matrix(expected, predicted)
print('')
print("confusion matrix")
print('')
print(results)

[1 1 0 1 0 0 1 0 0 0]

[1 0 0 1 0 0 1 1 1 0]

confusion matrix

[[4 2]
 [1 3]]


In [8]:
tp, fn, fp, tn = confusion_matrix(expected,predicted,labels=[1,0]).reshape(-1)
print('Outcome values : \n', tp, fn, fp, tn)

Outcome values : 
 3 1 2 4


True_positive: tp = 3 values

False_negatives: fn = 1 values
    
False_positive: fp = 2 values
    
True_negatives: tn = 4 values

In [9]:
matrix = classification_report(expected,predicted,labels=[1,0])
print('Classification report : \n',matrix)

Classification report : 
               precision    recall  f1-score   support

           1       0.60      0.75      0.67         4
           0       0.80      0.67      0.73         6

    accuracy                           0.70        10
   macro avg       0.70      0.71      0.70        10
weighted avg       0.72      0.70      0.70        10



__Question 2:__

Find out the recall, precision, F1 score and confusion matrix with picture

__from_the picture we infer that :__
    
true positives/cats are : 42
    
true negatives/dogs are : 32
    
false positives/cats are : 18
    
false negatives/dogs area: 8


In [14]:
TP = 42
TN = 32
FP = 18
FN = 8
print("TP=",TP )
print("TN=",TN )
print("FP=",FP )
print("FN=",FN )

TP= 42
TN= 32
FP= 18
FN= 8


# Accuracy

In [13]:
accuracy = (TP + TN)/(TP + TN + FP + FN)
print("ACCUREACY=",accuracy)

ACCUREACY= 0.74


# Precision

In [16]:
precision = TP / (TP + FP)
print(f"precision: {precision:4.2f}")

precision: 0.70


# Recall

In [15]:
recall = TP / (TP + FN)
print(f"recall: {recall:4.2f}")

recall: 0.84


# F1-score

In [21]:
f1_score = 2 * precision * recall / (precision + recall)
print(f"f1score: {f1_score:6.2f}")

f1score:   0.76
